var fruit = "Mango";
console.log("Is fruit == `Mango`? I predict true");
console.log(fruit == "Mango");
console.log("Is fruit == `Banana`? I predict False");
console.log(fruit == "Banana");
var cake = "Chocolate";
console.log("Is cake == `Chocolate`? I predict True.");
console.log(cake == "Chocolate");
console.log("Is cake == `Pineapple`? I predict False.");
console.log(cake == "Pineapple");
var car = "Ferrari";
console.log("Is car == `Ferrari`? I predict true.");
console.log(car == "Ferrari");
console.log("Is car == `Corolla`? I predict False.");
console.log(car == "Ferrari");
var stuff = "Lawn";
console.log("Is stuff == `Cotton`? I predict False.");
console.log(stuff == "Cotton");
console.log("Is stuff == `Lawn`? I predict True.");
console.log(stuff == "Lawn");
var season = "Summer";
console.log("Is season == `Summer`? I predict True.");
console.log(season == "Summer");
console.log("Is season == `Winter`? I predict False.");
console.log(season == "Winter");
